[development]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"
limits = { forms = 16777216 }

[staging]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "normal"
limits = { forms = 16777216 }

[production]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "critical"
limits = { forms = 16777216 }